### PR TITLE
Added final copy for Blu Dot Case Study (existed in Drafts) + Added Discovery Case Study from scratch

### PR DESCRIPTION
**Pull request by robinjohnson**
Added in content necessary to publish this case study

### CODE REVIEW

**Comment by robinjohnson** [comment]
@stewsmith - heyo! can we add this into the marketing site so I can send a staging/preview link to the Discovery team? thanks!

**Comment by srusonis** [comment]
@stewsmith Additional q - want to make sure we're getting the workflow correct here - we should author new pages in the Scribe repo, and then ask you to pull them into the marketing site repo? I think this should allow us to author pages using the same markdown format we've been getting used to.

Documentation is still in progress.

**Comment by stewsmith** [comment]
@robinjohnson Our staging is currently broken! AI is working on it now. Is there a staging from Scribe that you can use?

@srusonis Yup you've got the workflow right. I've made a basic wiki [here](https://github.com/optimizely/marketing-website/wiki/Scribe-%28Customer-Story-Templates%29) that I encourage you to edit!

**Comment by srusonis** [comment]
@stewsmith curses! that's too bad. let us know when it's back up?

@tomgenoni we have a couple of new pages we built with scribe and would like to preview. could you push these through so we can view them at the optimizely.github.io/scribe links?

**Comment by tomgenoni** [comment]
Merged and uploaded https://optimizely.github.io/scribe/stories/discovery.html

**Comment by srusonis** [comment]
Thanks, @tomgenoni!

@robinjohnson, does that work for you? my only issue is that it looks like the image isn't apprearing.

also, this is minor, but could you pull up the case study box module to right below the hero section? so before the [[intro]] section. just a small formatting thing to make this one more consistent with the rest of the case studies.

**Comment by robinjohnson** [comment]
@srusonis @stewsmith  - thanks for this! I've sent the link through to the Discovery team and will let you know when we are confirmed for approval. Will fix formatting as well.

**Comment by robinjohnson** [comment]
@stewsmith @srusonis @tomgenoni - As part of this pull request I also made copy changes to the already-existing Blu Dot case study (in the drafts folder), however, I don't see them reflected in the preview link. Let me know how to fix! Thanks!

https://optimizely.github.io/scribe/stories/bludot.html

**Comment by tomgenoni** [comment]
@robinjohnson I created the 'drafts' directory so that pages that were incomplete would not go out with the initial push (or any push). You can move the file into `/content/stories/` and you will see it locally.

**Comment by srusonis** [comment]
@robinjohnson I moved both discovery and blu dot to the drafts folder temporarily so we could push some other scribe changes without pushing those live.

I'll move them back tomorrow and ask to have them pushed to staging so you have both.

**Pull request merged**
