### PR TITLE
cd back out after gulp build is run

### PR DESCRIPTION
**Pull request by stewsmith**

### CODE REVIEW

**Comment by danoc** [comment]
LGTMM

**Comment by danoc** [comment]
I even merged it for you!

**Comment by stewsmith** [comment]
wow you are the workhorse of Optimizely

**Comment by stewsmith** [comment]
:construction_worker: + :horse:

**Comment by jsm** [comment]
FYI this kind of stuff is easily handled by pushd/popd

```
shell.echo(process.cwd()); // '/usr'
shell.pushd('/etc');       // '/etc /usr'
shell.echo(process.cwd()); // '/etc'
shell.popd();              // '/usr'
shell.echo(process.cwd()); // '/usr'
```

**Pull request merged**
